# This is a basic workflow to help you get started with Actions
name: Testing Actions

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  
  AWS_REGION : ap-southeast-2 #Change to reflect your Region

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:

  build:


    name: Build Image
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:

    - name: approval
      uses: trstringer/manual-approval@v1
      with:
            secret: ${{ github.TOKEN }}
            approvers: Joshua-Martin-CMD
            minimum-approvals: 1
            issue-title: "Deploying v1.3.5 to prod from staging"
            issue-body: "Please approve or deny the deployment of version v1.3.5."
            exclude-workflow-initiator-as-approver: false
            additional-approved-words: ''
            additional-denied-words: ''

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Extract branch name
      shell: bash
      run: |
        echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
        echo "GITHUB_WORKFLOW:$GITHUB_WORKFLOW"
        echo "GITHUB_EVENT_NAME:$GITHUB_EVENT_NAME"
        echo "GITHUB_EVENT_PATH:$GITHUB_EVENT_PATH"
        echo "GITHUB_WORKSPACE:$GITHUB_WORKSPACE"
        echo "GITHUB_SHA:$GITHUB_SHA"
        echo "GITHUB_REF:$GITHUB_REF"
        echo "GITHUB_HEAD_REF:$GITHUB_HEAD_REF"
        echo "GITHUB_TAG:${GITHUB_HEAD_REF##*/}"
    
    - name: Print complete webhook event payload
      run: cat $GITHUB_EVENT_PATH