name: Deploy to ECR

on:
 
  pull_request:
    branches: [ main ]

env:
  AWS_REGION : ap-southeast-2

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
   
jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Extract branch name
      shell: bash
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
      id: extract_branch

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
          role-to-assume: arn:aws:iam::318690755185:role/GitHubAction-AssumeRoleWithAction #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      # Hello from AWS: WhoAmI
    - name: Sts GetCallerIdentity
      run: |
          aws sts get-caller-identity

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: wilson-wbd-api
      run: |
        echo running on branch ${GITHUB_REF##*/}
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/} .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/}